imports:
  - { resource: parameters.yml }

docker_base:
    root_password: "%mysql_root_password%"
    mysql_database: "%mysql_database%"
    mysql_user: "%mysql_user%"
    mysql_password: "%mysql_password%"